import http from './httpService';
import config from '../config.json';
import jwtDecode from 'jwt-decode';


const apiEndpoint = config.apiUrl + "/auth";
 
export async function login(email,password){
     const {data:jwt} = await http.post(apiEndpoint, {email,password});
    localStorage.setItem('token', jwt); //token from server for authentication is stored in a local storage of my browser.
};

export function loginWithJwt(jwt) {

    localStorage.setItem("token", jwt); // this stores the x-auth-token generated by server in a local storage in the browser


}

export function logout() {
    localStorage.removeItem('token'); // this removes the token from local storage in browser....this effectively signs out the user
}

export function getCurrentUser() {
    try {
        const jwt = localStorage.getItem("token"); // A jason web token has to be decoded and displayed. install the library jwt-decode in terminal
        return jwtDecode(jwt); // get user token and return
        
         }
         catch (ex) {
            return null;
         }
}

export default {
    login,
    loginWithJwt,
    logout,
    getCurrentUser
};